@startuml
!include style.puml
skinparam BoxPadding 0
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "e:ExportCommand" as ExportCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Commons COMMONS_COLOR_T1
participant ":Commons" as Commons COMMONS_COLOR
end box

[-> LogicManager : execute(export)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(export)
activate AddressBookParser

create ExportCommand
AddressBookParser -> ExportCommand
activate ExportCommand

ExportCommand --> AddressBookParser
deactivate ExportCommand

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> ExportCommand : execute()
activate ExportCommand

ExportCommand -> Model : getPersonList()
activate Model

Model -> Commons : writeContactsToCsv(path, contacts)
activate Commons

Commons --> Model : result
deactivate Commons
ExportCommand -[hidden]-> LogicManager : result
destroy Commons

Model --> ExportCommand
deactivate Model

ExportCommand --> LogicManager : PersonList
deactivate ExportCommand
ExportCommand -[hidden]-> LogicManager : result
destroy ExportCommand

[<--LogicManager
deactivate LogicManager
@enduml
