@startuml
!include style.puml
skinparam BoxPadding 0
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "i:ImportCommand" as ImportCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Commons COMMONS_COLOR_T1
participant ":Commons" as Commons COMMONS_COLOR
end box

[-> LogicManager : execute(import path)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(immport)
activate AddressBookParser

create ImportCommand
AddressBookParser -> ImportCommand
activate ImportCommand

ImportCommand --> AddressBookParser
deactivate ImportCommand

AddressBookParser --> LogicManager : i
deactivate AddressBookParser

LogicManager -> ImportCommand : execute()
activate ImportCommand

ImportCommand -> Commons : readContactsFromCsv(path)
activate Commons

Commons --> ImportCommand : contacts
deactivate Commons
ImportCommand -[hidden]-> LogicManager : result
destroy Commons

loop for each person in contacts
ImportCommand -> Model : addPerson(p)
activate Model

Model --> ImportCommand
deactivate Model
end

ImportCommand --> LogicManager :
deactivate ImportCommand
ImportCommand -[hidden]-> LogicManager : result
destroy ImportCommand

[<--LogicManager
deactivate LogicManager
@enduml
