@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes import command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([detects csv file from path])
    :Gets all contacts from the csv file;
    :Filters contacts for duplicates and errors;
    :Add the verified contacts to the Address book;
else ([else])
endif
stop
@enduml
